# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
b <- board_url(c(seattle_model = "https://pub.demo.posit.team/public/seattle-rstats-model-pin/"))
v <- vetiver_pin_read(b, "seattle_model")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
