# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
library(dplyr)
library(DALEX)
library(DALEXtra)

# Packages needed to generate model predictions
if (FALSE) {
  library(parsnip)
  library(ranger)
  library(workflows)
}

b <- board_connect(auth = "envvar", server = "https://pub.vetiver.posit.team/")
v <- vetiver_pin_read(b, "bensoltoff/seattle-housing-rf", version = "129")

# generate explanations for predictions
board <- board_url(c(
  shap_explainer = "https://pub.demo.posit.team/public/seattle-shap-rstats/"
))
explainer <- pin_read(board, "shap_explainer")

handler_explain <- function(req) {
  new_data <- req$body
  new_data <- vetiver_type_convert(new_data, v$prototype)
  shap <- predict_parts(explainer, new_data, type = "shap", B = 5)
  plot(shap)
}

#* @plumber
function(pr) {
  pr |>
    vetiver_api(v) |>
    pr_post(path = "/explain", handler = handler_explain, serializer = "png")
}
